### ISSUE TITLE
Prebuilt binary not remembering logins [Manjaro/Phosh/Pinephone]

### ISSUE THREAD

**Issue by rapidewilson** [diamondburned/gtkcord4#18]
My first github issue post so please pull me up on any etiquette issues. 

Launching the prebuilt binary results in the following error from the terminal 
`2022/05/14 11:52:15 failed to read user.css: open /home/manjaro/.config/gtkcord4/user.css: no such file or directory`

Binary has all permissions. 
Making a blank user.css file satisfies the requirement and sees the message go away, but the file is never populated with anything.

**Comment by diamondburned** [comment]
The error isn't relevant to the issue here.

Do you have a keyring? If not, you'll need to use a password to remember the account, which can be restored by clicking the Decrypt button. The password may be empty.

**Comment by rapidewilson** [comment]
Ahh thanks for the clarification. So, I do have a keyring, and it does ask permissions to it, but when given the password, it doesn't remember my login. 
Does the 'remember me' stuff only work for 'token' based login? Or should it remember email/password combos too?

**Comment by rapidewilson** [comment]
`[manjaro@manjaro-arm bin]$ ./gtkcord4
2022/05/15 14:09:09 Warning: Gsk: Unrecognized renderer "ngl". Try GSK_RENDERER=help
2022/05/15 14:09:09 note: account not found from driver: key not found
2022/05/15 14:09:09 Warning: Gtk: GtkGizmo 0xffff581313f0 (progress) reported min width -2, but sizes must be >= 0
`

Some extra output for you if any of this is helpful.

**Comment by diamondburned** [comment]
> Does the 'remember me' stuff only work for 'token' based login? Or should it remember email/password combos too?

The regular email/password login should give the client the token which it uses to store the account, but I never actually tested that.

If the Remember me checkbox never prompted you for a password by itself, then it's probably using the system keyring. The dialog made by gtkcord4 should look something like this (except it says Encrypt instead of Decrypt):

![image](https://user-images.githubusercontent.com/8463786/168496732-aa17e228-a1ec-4208-8d47-c0abb6025316.png)

If gtkcord4 did prompt you the password by itself, then you'll need to use the Decrypt button to get the account:

![image](https://user-images.githubusercontent.com/8463786/168496773-95f7a104-d117-45fc-8b18-1f3ecaebc323.png)

Otherwise, everything should be automatic. I'm seeing a `note: account not found from driver: key not found`, which tells me that it's not in the system keyring.

**Comment by rapidewilson** [comment]
Okay, seems I still had some stuff to learn. It's all working fine now, hadn't got my keyring set up properly. 
It's remembering my login now, so thanks for the help and pointing in the right directions!

**Comment by JosefLitos** [comment]
How do we pass the constant Decrypt button clicking? Why can't we just login when we gave the token and set no encrypt password?

**Comment by diamondburned** [comment]
It already does this with a keyring daemon, but iirc it doesn't do that yet with the encrypted token file. I'm not even sure if it's capable of knowing if the file requires password.
