### ISSUE TITLE
gtkcord4 not using libadwaita's theme

### ISSUE THREAD

**Issue by JanzenJohn** [diamondburned/gtkcord4#24]
Using gnome 42.1 on Archlinux

gtkcord4 uses white theme while firefox / gnome-console uses dark theme as selected in gnome settings

**Comment by diamondburned** [comment]
This might be because GNOME 42 only cares about libadwaita, and gtkcord4 does not use libadwaita.

Try setting `$GTK_THEME`.

**Comment by JanzenJohn** [comment]
is libadwaita support planned ?

**Comment by diamondburned** [comment]
No. I don't want to use libadwaita anymore after they decided to force the theme on my application, even though I am the developer, not them.

**Comment by diamondburned** [comment]
That is not to say gtkcord4 doesn't already support mobile, though. People are using it on mobile just fine.

**Comment by JanzenJohn** [comment]
is a dark theme planned yet ?
would be nice to have dev approved dark mode, where everything is planned to look dark

**Comment by diamondburned** [comment]
The screenshot that I have is dark themed. Again, this is a GTK4 application that follows the system theme, and if your system theme is dark, it should be dark too.

If Tweaks doesn't work, try `$GTK_THEME`. The GNOME developers killing ways to change themes is not a problem that I can help.

**Comment by TriVoxel** [comment]
I experience this issue on Gnome 42 as well. I have the system settings set to dark as well as Gnome tweaks. I don't know about the $gtk_theme hack. It seems the application isn't recognizing the normal global variables for light/dark themes. Maybe you could include an option to use libadwaita as some people like it (if possible), or to toggle in preferences like normal Discord?

**Comment by diamondburned** [comment]
> gtk4 app (not libadwaita):

GNOME Tweaks actually uses libadwaita afaict.

You can try running something like gtk4-icon-browser.

**Comment by diamondburned** [comment]
Seeing how your Tweaks has a GTK3 theme for "Legacy Applications", I'm guessing that GNOME 42 straight up does not have a way to change the GTK4 theme.

**Comment by diamondburned** [comment]
> Maybe you could include an option to use libadwaita as some people like it (if possible), or to toggle dark mode in preferences like normal Discord?

Adding dark mode using Discord's user settings seems like the easiest solution.

There's no easy way to just "toggle" libadwaita, and making gtkcord4 use it would either require rebuilding the whole program with libadwaita linked or somehow inject it using weird LD_PRELOAD magic fuckery and patching the machine code in the binary.

**Comment by diamondburned** [comment]
gtkcord4 now accepts a `-tags libadwaita`, which causes it to be built with libadwaita support.

Release binaries will not include libadwaita. Since I don't use libadwaita, expect certain things to look out of place. If that happens, do make an issue about it.

**Comment by DodoLeDev** [comment]
### Hi @diamondburned!
I've tried both versions of your GTKcord app (gtk4 & Libadwaita ones), and I don't understand the reasons that prevent you from completely moving to Libadwaita… :thinking:

The Libadwaita version seems so polished! :star_struck: And I don't see any major graphical difference…
If you worry about not being able to control the theme used by your app, here are some links that can help you:
- :link: [Force the dark theme for your Libadwaita app](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.2/method.StyleManager.set_color_scheme.html)
- :link: [Setting a custom Libadwaita theme](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/styles-and-appearance.html#custom-styles)

*Hoping to have helped you!*

**Comment by diamondburned** [comment]
> I've tried both versions of your GTKcord app (gtk4 & Libadwaita ones), and I don't understand the reasons that prevent you from completely moving to Libadwaita… thinking

The reason is mostly an opinionated one. See these issues:

- https://github.com/diamondburned/gtkcord4/issues/24
- https://github.com/diamondburned/gtkcord4/issues/72

**Comment by TriVoxel** [comment]
> > gtk4 app (not libadwaita):
> 
> GNOME Tweaks actually uses libadwaita afaict.
> 
> You can try running something like gtk4-icon-browser.

Actually, I can confirm Gnome Tweaks does not use LibAdwaita (yet). It uses GTK3. The reason it looks like LibAdwaita is because I have the GTK3 theme "adwgtk3" installed as you can see under the "legacy applications" dropdown. If I change that theme to a different GTK3 theme, then Gnome Tweaks will change as well. For some reason, your app does not conform to the system light/dark settings. It does not care what you set in the Gnome settings, nor does it care what you set the GTK3 theme to in Gnome Tweaks. It completely ignores all user preferences and forces the default look.

I understand being reluctant to conform to emerging interface standards, but completely breaking consistency with the rest of the system feels like a step in the wrong direction to me.

As a side note, it seems that LibAdwaita is the future of GTK. And honestly, I support it. I never liked having apps completely break when you install a theme. Some themes work, others don't. Also, there has always been a strange disconnect between theming native apps, flatpak apps, and snap apps. LibAdwaita gives developers a common ground for building interfaces, with predictable behaviour between light and dark themes. It is nice for the user, too, as they get the benefit of having elegant, funtional applications. Also, with apps such as Gradience, the user can easily theme all LibAdwaita apps themselves and adjust the colors and highlights without worrying about breaking app compatibility or breaking the interface altogether. It, to me, feels like a nice compromise between the freedom of customization, and the ease of developing an app that will work in a predictable and consistent manner. You can still theme LibAdwaita apps, but it is much safer and will not destroy all usability like the old days of GTK3 theming. I used to theme GTK3 and Gnome 3 a lot, I don't miss it.

**Comment by diamondburned** [comment]
> It does not care what you set in the Gnome settings, nor does it care what you set the GTK3 theme to in Gnome Tweaks. It completely ignores all user preferences and forces the default look.

No.

GNOME Tweaks has no way of setting GTK4 theme, and GNOME's settings tweak libadwaita.

GNOME refuses to provide a way to change GTK4 themes. This is not my problem, but GNOME Foundation's, or rather the user.

> I understand being reluctant to conform to emerging interface standards, but completely breaking consistency with the rest of the system feels like a step in the wrong direction to me.

This is not "a step". GTK4 does not depend on libadwaita, so there's no reason for me to add it in. Whether I include the library or not is the developer's (my) decision. It's not a step anywhere.

Again, it's not my problem that GNOME does not provide any way to theme GTK4. It's the GNOME Foundation's. GNOME could have easily added one line of code to change the GTK4 settings to also be dark, but they didn't, even when they know that GTK4 apps exist, and that's not my problem. This is a deliberate decision made by the GNOME team.

I didn't write this app with the intention of fitting it into the GNOME application ecosystem. I wrote this app with the intention of fitting with what my system has, and my system has a dark-by-default GTK4 theme since the start.

> As a side note, it seems that LibAdwaita is the future of GTK.

Good for you. libadwaita goes against what I support, and until they have libadwaita as a hard dependency of GTK4, I'm not willing to include it by default.

When they do, I might even stop using GTK.

**Comment by diamondburned** [comment]
As a side note, gtkcord4 should already tweak its own GTK4 settings to be dark if Discord's user preference is set to dark. If this does not work, you can open an issue about it.

**Comment by TriVoxel** [comment]
I'm not trying to attack you, I don't know why you are so upset. I'm simply trying to rationalize this conversation, and share my opinions and thoughts. I'm trying to suggest changes, not force you to develop your app my way. It seems that something about LibAdwaita frustrates or angers you on a personal level. Also, as far as dark/light theming with the system setting goes, I kinda assumed you could read the global setting for light/dark and use that to determine the program's theme. I know it's technically a LibAdwaita feature, but all the Gnome DConf settings are public.

Look, I think what you have here is cool, don't get me wrong. However, I think you are going about this in a bad way. You seem to be developing this open source app for yourself and only yourself. I understand wanting to do things a certain way, but lashing out and attacking the Gnome developers, your users, and going so far as to accuse others of ruining your own application? Feeling like your app being broken on Gnome is somehow their fault? What is going on? Why do you care so much what the Gnome devs think, or what your users think? If you hate feedback so much, if you don't want anyone else to use your application, if you only want the app to work properly on YOUR specific desktop and not on the mainstream desktops, why even release it? You seem reluctant to take any feedback in the issues I've seen, and are actively arguing and defending your rationale even though people are just offering their thoughts and opinions. I don't think it's wrong to make a GTK4 app at all. I think it's really interesting. I was only asking that you find a way to make it so that the vast majority of GTK users could appreciate all the work you've put into the app by making it theme. I don't really CARE if an app is built in LibAdwaita, or GTK3, or GTK4, or even GTK2 ffs. I only care that it works properly and matches the rest of my system. I assumed releasing a LibAdw version would be the easiest way to appease this userbase, but apparently not. Why is this such an issue? You act as though we are trying to force your hand, we're merely asking you to CONSIDER THE USER EXPERIENCE. Come on. Do whatever with your app, I was only trying to help, and so was everyone else who asked for LibAdw. We don't actually care about that library, we just want the app to look right. Clearly some documentation for setting a GTK4 theme is needed, or something. But not this, not harassing developers and users because your app doesn't work right for anyone but you.

**Comment by diamondburned** [comment]
> Also, as far as dark/light theming with the system setting goes, I kinda assumed you could read the global setting for light/dark and use that to determine the program's theme. I know it's technically a LibAdwaita feature, but all the Gnome DConf settings are public.

GTK does this by default for 3 and 4. The problem isn't gtkcord4 not reading it, it's that GNOME refuses to add a switch to change it. Again, this has to do with the GNOME Foundation.

> Look, I think what you have here is cool, don't get me wrong. However, I think you are going about this in a bad way. You seem to be developing this open source app for yourself and only yourself. I understand wanting to do things a certain way, but lashing out and attacking the Gnome developers, your users, and going so far as to accuse others of ruining your own application? Feeling like your app being broken on Gnome is somehow their fault? What is going on? Why do you care so much what the Gnome devs think, or what your users think? If you hate feedback so much, if you don't want anyone else to use your application, if you only want the app to work properly on YOUR specific desktop and not on the mainstream desktops, why even release it? You seem reluctant to take any feedback in the issues I've seen, and are actively arguing and defending your rationale even though people are just offering their thoughts and opinions. I don't think it's wrong to make a GTK4 app at all. I think it's really interesting. I was only asking that you find a way to make it so that the vast majority of GTK users could appreciate all the work you've put into the app by making it theme. I don't really CARE if an app is built in LibAdwaita, or GTK3, or GTK4, or even GTK2. I only care that it works properly and matches the rest of my system. I assumed releasing a LibAdw version would be the easiest way to appease this userbase, but apparently not. Why is this such an issue? You act as though we are trying to force your hand, we're merely asking you to CONSIDER THE USER EXPERIENCE. Come on. Do whatever with your app, I was only trying to help, and so was everyone else who asked for LibAdw. We don't actually care about that library, we just want the app to look right. Clearly some documentation for setting a GTK4 theme is needed, or something. But not this, not harassing developers and users because your app doesn't work right for anyone but you.

I'm not attacking anyone. I'm telling people to complain to the GNOME Foundation instead. It has been shown from time to time that they do not care about the opinions of the minority unless it becomes a major deal, and I'm not willing to go through that effort.

I've talked to several GNOME and libadwaita developers and have made up my mind.

> I mean no offense, I really like your vision and reasoning, but I feel like this is just the wrong way to go about it. Couldn't you ask the Gnome devs to fix this in a bug report, fix it yourself in a pull request, work around the issue in your app? There are solutions to this problem. I know that your priority is to make this app for your own system, but it would be nice if others could enjoy it, too.

I shouldn't be the person to do it. And I have talked to GNOME developers about this issue. Their stance is clear, and so is mine. Anything in-between is simply unfortunate.

If the community gets fed up by this change and decides to press GNOME for it, then great! I'm not involved in that. My system works without needing to care if an application uses libadwaita or not, and I'm keeping it that way.

> Don't forget, Gnome Tweaks has always been a hack, and they probably didn't add the GTK4 stuff because the app is barely maintained and doesn't get the same treatment as all the rest of the Gnome apps. It has always been this way.

It has always been a hack. It is also one of the things that keep me on the GNOME platform in the first place. I wouldn't want to use GNOME otherwise, and I probably wouldn't even use GTK anymore. Even if it's a hack, it's one that keeps people like me on the platform.

I wouldn't be surprise that one day, the GNOME developers will decide to pull the plug on GNOME Tweaks, and that's fine. However, I'll likely stop using the platform entirely when that happens, and it would also likely mean that I will stop developing this project. That is simply my stance.

> I am saying that LibAdw is not meant to attack anyone, but rather to help developers and users. I don't think there is a conspiracy to break app compatibility on the Gnome platform. I'm pretty sure all of Gnome's resources have been put into LibAdwaita and the Gnome desktop and apps, and very little has been put into legacy theming, GTK4 theming, and the Tweaks app especially. Just playing devil's advocate here.

I'm genuinely not even sure where this came from. I don't think anyone thought that libadwaita is meant to attack someone, and I certainly don't think it's some mean conspiracy.

Once again, I'm only making it clear that my stance is different from the GNOME Foundation's. At the end of the day, some fighting is bound to happen, and the users will probably suffer from that. That's just how open source projects fundamentally work, though: developers disagree and do their own things. That's why we have gcc and clang; that's why we have Go and Rust; etc.

I don't think it's right to force someone to change their opinions on something, even if it's by "playing devil's advocate" or thinking it's some big mean conspiracy. That's why I kept my discussions with the GNOME team to a small discussion and went on with my way once we reached the disagreement. I'm not going to spam comments on their issues; I'm not going to complain repeatedly to them over email/IRC/Matrix; I'm not going to bother them. Their stance is clear, and so is mine. Anything that happens in-between is simply unfortunate.

**Comment by TriVoxel** [comment]
Fair enough. Thank you for your time, and for doing what you think is best. I appreciate it. I felt like there was some disrespect or anger, but then again, that is the downside of communicating through text. I hope Gnome will work towards support all applications (like GTK4) better. I hope that we continue to see improvements to user theming in the future, too.

I will say, Gnome has outdone themselves in the stability and consistency of Gnome 42 and now 43. I know it changes the game of customization, but I personally like it. I'll say that much. You can still majorly overhaul the look and feel with extensions, and you can still change the colors of your theme at will using the Gradience app or by installing a LibAdwaita theme pack. I know you disagree with it, but if you have some free time, maybe give Fedora 37 a try in a VM or something, it's not all bad. They haven't put all their eggs in this basket for no reason. They just have a very clear vision, and will stubbornly march towards it no matter what.

Gnome has ALWAYS done things that either piss people off or outright ruined their desktop. Although, I think that their stubborn vision has finally come to a head. They have finally realized that unified desktop that they've been working so hard for since Gnome 3. I disliked Gnome for the longest time, now it's my favorite desktop. Hate to see it still struggle, but am overall still happy with it. I think developers need to have the freedom to use whatever GTK libraries they want, but at least the stock desktop doesn't suck, and it's easier than ever to theme all the apps at once.

Thanks again for taking the time to make this app and to respond to my criticisms. Hopefully Gnome will fix the issues we've mentioned. Seems like a no-brainer since its GTK4 compatibility we're talking about here. Anyway, take care!
