### ISSUE TITLE
Question about limitations.

### ISSUE THREAD

**Issue by mutexdeveloper** [diamondburned/gtkcord4#92]
Hey, This project is very interesting and I love how compact it is.
Although I think its a little too compact, The functionality for a friends list / leaving and joining servers / reacting is missing alongside some other important features,
Is there any plans to extend the functionality, A way of doing this could be to add features to the app itself (obviously) or maybe even adding plugin support could be the solution and allowing the community to add the features.
Anyway, Thanks for making this.

**Comment by diamondburned** [comment]
I'm unsure about adding plugins, since it'll require a lot of effort, but there are more bug fixes to be done and features to be added before I want to add plugins. I'm ironing the app as I use it, but I don't want the app to be a full replacement, since that's a lot more work than just a bare app.

If you want to give a try at writing Go, feel free to fork it, add more features, then open a pull request.

I'll be closing this issue since the question is answered, but if you have any feature requests, please open a separate issue for each of them.
